[package]
name = "respawn"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.24.1"
clap = { version = "3.2.8", features = ["derive"] }
